python/astra/experimental.pyx

This is a fix for issue #21 . It simply removes all code in experimental.pyx when not building with CUDA.

Fix experimental.pyx for non-CUDA compilation

---

build/linux/Makefile.in
python/conda/build.sh
python/conda/libastra/build.sh
python/conda/libastra/meta.yaml

After cd395d2af23530f9da471fd6c512e9890c08f69d, the C++ library does not depend on libpython anymore, so we can split the conda package into two parts: a C++ library part that does not depend on the specific python version used (libastra), and the python interface that does depend on it (astra-toolbox). The advantage is that we don't need to distribute multiple versions of the c++ library with CUDA dependencies (which is quite a big tarball) for each combination of python version and numpy version.
The current conda build script uses the latest master branch, and should be changed to specifically use the correct git tag when the next version of astra will be released.

Split conda package into c++ lib and python parts

---

cuda/2d/sart.cu
cuda/2d/sart.h
cuda/2d/sirt.cu
cuda/2d/sirt.h
cuda/3d/astra3d.cu
cuda/3d/astra3d.h
cuda/3d/sirt3d.cu
cuda/3d/sirt3d.h
include/astra/ArtAlgorithm.h
include/astra/CudaReconstructionAlgorithm2D.h
include/astra/CudaSartAlgorithm.h
include/astra/CudaSirtAlgorithm.h
include/astra/CudaSirtAlgorithm3D.h
include/astra/DataProjectorPolicies.h
include/astra/DataProjectorPolicies.inl
include/astra/SartAlgorithm.h
include/astra/SirtAlgorithm.h
src/ArtAlgorithm.cpp
src/CudaReconstructionAlgorithm2D.cpp
src/CudaSartAlgorithm.cpp
src/CudaSirtAlgorithm.cpp
src/CudaSirtAlgorithm3D.cpp
src/SartAlgorithm.cpp
src/SirtAlgorithm.cpp

This adds a `Relaxation` option to SIRT, SIRT_CUDA, SIRT3D_CUDA, SART, SART_CUDA.
It also renames the `Lambda` option of ART to `Relaxation` (while keeping `Lambda` as a fallback for backward compatibility).

Add relaxation factor option to SIRT, SART

---

include/astra/Fourier.h
src/FilteredBackProjectionAlgorithm.cpp
src/Fourier.cpp

This PR changes the CPU FFT implementation to the one of http://www.kurims.kyoto-u.ac.jp/~ooura/fft.html .
This fixes #45 and is also about 2x faster for large detectors on my machine.

Change CPU FFT implementation

---

python/astra/optomo.py
samples/python/s009_projection_matrix.py
samples/python/s015_fp_bp.py
samples/python/s017_OpTomo.py

Following the discussion in #47, this PR changes `flatten` to `ravel` in the Python code to remove unnecessary copies of data. The most important change is in `OpTomo`, where it will probably result in a significant speedup for large data. The other changes are in the samples, where it doesn't really make a difference.

Change flatten to ravel in Python code

---

python/astra/data3d_c.pyx

This makes the output directly usable in numpy commands like zeros, reshape.
We were not using data3d.dimensions ourselves, as far as I can tell.

Reverse output of astra.data3d.dimensions

---

build/linux/Makefile.in
python/astra/extrautils.pyx

In the current master, only the C++ library will be compiled with the `CXX` variable that is set during the `configure` call, which will lead to problems when the `CXX` gcc version is incompatible with the default gcc version (see #44 for an example). This PR fixes this problem by passing the `CXX` setting to the python compilation call.

Use CXX for Python compilation as well

---

python/astra/optomo.py
samples/python/s018_plugin.py

This allows more efficient use of allocated arrays.
For example:
```python
v = astra.data3d.get_shared(self.vid)
s = astra.data3d.get_shared(self.sid)
tv = np.zeros(v.shape, dtype=np.float32)
ts = np.zeros(s.shape, dtype=np.float32)
W = self.W
C = self.C
R = self.R
for i in range(its):
W.FP(v,out=ts)
ts -= s
ts *= R # ts = R * (W*v - s)
W.BP(ts,out=tv)
tv *= C
v -= tv
```

Give OpTomo FP/BP functions with optional out argument

---

include/astra/Singleton.h

That way, the call to new is always executed by code inside libastra.
This avoids the situation where a singleton gets created by a copy
of the constructor linked into an object file outside of libastra, such
as a .mex file, which would then also cause the vtable to be outside of
libastra. This situation would cause issues when .mex files are unloaded.

Avoid defining singleton construction in header file

---

include/astra/Utilities.h
matlab/mex/mexHelpFunctions.cpp
python/astra/src/PythonPluginAlgorithm.cpp
src/Utilities.cpp

This changes a leftover use of `strtod` to `StringUtil::stringToDouble`, and replaces use of `boost::split` by a new `StringUtil::splitString` (`boost::split` was causing inexplicable undefined behaviour on some setups.)

Minor string parsing changes

---

src/FanFlatBeamLineKernelProjector2D.cpp
src/FanFlatBeamStripKernelProjector2D.cpp
src/ParallelBeamBlobKernelProjector2D.cpp
src/ParallelBeamLineKernelProjector2D.cpp
src/ParallelBeamLinearKernelProjector2D.cpp
src/ParallelBeamStripKernelProjector2D.cpp

This patch fix ASTRA build with MS VS 2015 CE. 
Without this changes Visual Studio report about following errors: 'functions min and max not defined in this scope'

Fix build with MS VS 2015 CE

---

build/linux/Makefile.in
build/linux/configure.ac
matlab/mex/mexDataManagerHelpFunctions.cpp
matlab/mex/octave_support.cpp

This needs testing, especially the `data3d('link')` support, both in Octave and in Matlab.
Based on initial patch by @kalvdans at #13.

Add experimental support for Octave

---

.travis.yml
README.md
README.txt
build/linux/Makefile.in
build/linux/configure.ac
python/builder.py
python/conda/build.sh

There are now three ways of installing from configure/make:
./configure --with-install-type=prefix (default)
libraries go into \@prefix@/lib (or lib64)
matlab tools/mex go into \@prefix@/share/astra/matlab
octave tools/mex go into \@prefix@/share/astra/octave
python module goes into site-packages
./configure --with-install-type=dir
libraries go into \@prefix@/lib
matlab tools/mex go into \@prefix@/matlab
octave tools/mex go into \@prefix@/octave
python module goes into \@prefix@/python
./configure --with-install-type=module
matlab tools/mex go into \@prefix@/matlab
octave tools/mex go into \@prefix@/octave
python module goes into site-packages
library is installed along with the matlab/octave/python module(s), with rpath

Overhaul package installation

---

cuda/3d/astra3d.cu
cuda/3d/astra3d.h
cuda/3d/fdk.cu
cuda/3d/fdk.h
include/astra/CudaFDKAlgorithm3D.h
src/CudaFDKAlgorithm3D.cpp

This PR adds an option to specify a custom filter for FDK using a 2D geometry, like:
``` python
pg = astra.create_proj_geom('cone', 1, 1, 128, 128, np.linspace(0,2*np.pi,64,False), 5*128, 0)
vg = astra.create_vol_geom(128,128,128)
pid = astra.create_projector('cuda3d',pg,vg)
w = astra.OpTomo(pid)
r = w.reconstruct('FDK_CUDA', s)
pgf = astra.create_proj_geom('parallel',1.0,129,np.linspace(0,2*np.pi,64,False))
fid = astra.data2d.create('-sino', pgf, np.ones((64,129)))
r = w.reconstruct('FDK_CUDA',s,extraOptions={'FilterSinogramId':fid})
```
This will make it possible to try advanced filter-based method with FDK.

Add option to specify custom filter for FDK

---

cuda/3d/mem3d.cu
cuda/3d/mem3d.h
include/astra/CudaProjector3D.h
src/CompositeGeometryManager.cpp
src/CudaProjector3D.cpp

It is now exposed via the new DensityWeighting option of CudaProjector3D. This is a bit ugly, and will probably disappear in astra-2.0 in favour of a cleaner alternative, but this lets you use the 1/r^2 factor in cone_bp, as long as the source-origin distance is constant.
Quick'n'dirty way to get it in ODL:
In `astra_setup.astra_projector` add this option to `proj_cfg`:
if proj_type == 'cone' or proj_type == 'cone_vec':
astra_ver_num = astra.astra.version()
astra_version = '.'.join([str(astra_ver_num // 100),
str(astra_ver_num % 100)])
if parse_version(astra_version) >= parse_version('1.8'):
proj_cfg['options'] = { 'DensityWeighting': True }
In `astra_cuda.astra_cuda_back_projector` add an extra scaling factor in cone/helical (relative to branch issue-724__astra_scaling_fixed): …

Expose the density weighting option of cone_bp

---

python/conda/bld.bat
python/conda/libastra/bld.bat
python/conda/libastra/meta.yaml
python/conda/linux_release/README.txt
python/conda/linux_release/buildenv/Dockerfile
python/conda/linux_release/builder/Dockerfile
python/conda/linux_release/release.sh
python/conda/meta.yaml

This is a build environment based on Debian 7 + CUDA 5.5 that produces conda packages for libastra and astra-toolbox.
On the conda side, the only difference with the files in the `python/conda` directory is a run-time dependency on the cudatoolkit=5.5.1 conda package to avoid shipping the libraries ourselves.
Also included is a win-64 / py35 conda build recipe.

Add scripts for building conda packages using Docker

---

python/conda/linux_release/builder/Dockerfile
python/conda/linux_release/release.sh
python/conda/meta.yaml

Current conda packages of ASTRA do not specify the numpy version that they were built with. Since we link to specific versions of numpy, the current packages will probably not work when using a different numpy version than the one it was compiled with.
This PR fixes this problem by using `numpy x.x` in the `meta.yaml` file (see [here](http://conda.pydata.org/docs/building/meta-yaml.html)). This requires the `conda-build` call to supply the numpy version to build with on the command line (e.g., `--numpy 1.11`).

Use specific numpy version in conda package

---

matlab/tools/opTomo.m

The opTomo operator has the volume and projection geometries as properties ( SetAccess = private, GetAccess = public ).
This way you can all easily access all information about the geometry if you passed the opTomo object to a function.

added vol_geom and proj_geom to the properties

---

README.md
README.txt

The astra_vc14 solution expects libraries in lib\x64 folder, yet READMEs stated bin\x64. This corrects the READMEs.

README: boost lib path correction

---

python/conda/linux_release/buildenv/Dockerfile

This fixes the issue where cudatoolkit=8.0 would not install any more
with recent versions of conda. Also, no corruption appears to take
place while downloading packages.
I have run the build process in a docker container. I get 19 outputs, a lot of warnings, but there appear to be no error messages.

Use recent version of conda during linux conda-build

---

python/conda/astra-toolbox/conda_build_config_py27.yaml
python/conda/astra-toolbox/conda_build_config_py35.yaml
python/conda/astra-toolbox/conda_build_config_py36.yaml
python/conda/astra-toolbox/conda_build_config_py37.yaml
python/conda/astra-toolbox/meta.yaml
python/conda/libastra/build.sh
python/conda/libastra/linux_build_config.yaml
python/conda/libastra/meta.yaml
python/conda/linux_release/buildenv/build.sh

For both libastra and astra-toolbox:
1) We do not use script_env to set CC/CXX anymore, since the compilers
are installed by conda.
2) The build string is made useful by including either the python+numpy
version or the cudatoolkit version that the package was built with.
3) Some clean-up of build.sh in buildenv/
For libastra:
1) The libastra.so is built with the conda C/C++ compiler
toolchain. This has two benefits:
1) The rpath of libastra.so is set to $ORIGIN, which makes linking
easier for dependent packages.
2) libastra.so is linkable against ancient versions of glibc. With
old versions of memcpy.
2) The C/C++ compiler version is fixed to 5.4.0
3) In libastra/build.sh, we rename $CONDA_PREFIX to
$PREFIX. Apparently, this is how it is supposed to be done. For me,
$CONDA_PREFIX was …

Use conda compiler toolchain for conda builds

---

cuda/2d/par_fp.cu

Arrays were dynamically allocated in the function convertAndUploadAngles, but were not deallocated, resulting in a memory leak. At the end of this function I now delete [] these arrays, fixing the memory leak.

Fix memory leak in CUDA 2D par_fp

---

python/astra/optomo.py

A minor modification to `optomo.py` to solve [this issue](https://github.com/astra-toolbox/astra-toolbox/issues/240).
This PR enables the use of OpTomo in algorithms that internally need the Hermitian adjoint. If you define `W = astra.OpTomo(proj_id)` then you can now do `W.H @ x` or `W.adjoint() @ x`, with the same effect as `W.T @ x` and `W.transpose() @ x`. The adjoint is equal to the transpose because the operator is real.
Before this PR, `W.H` did return an operator, but it throws an error if you multiply it with a vector.

Implemented _adjoint of OpTomo by equating it to _transpose

---

src/CudaSartAlgorithm.cpp

Addresses #346. Not the most elegant solution, but should do the job for now.

Fix SART_CUDA algorithm crash when sinogram mask option is provided

---

python/builder.py

Fixes build error: each element of 'ext_modules' option must be an Extension instance or 2-tuple
See also: https://stackoverflow.com/questions/21594925
`make` fails for me without this change.

Reorder setuptools import

---

cuda/2d/arith.cu
cuda/2d/fan_bp.cu
cuda/2d/fan_fp.cu
cuda/2d/fft.cu
cuda/2d/par_bp.cu
cuda/2d/par_fp.cu
cuda/2d/sart.cu
cuda/2d/util.cu
cuda/3d/arith3d.cu
cuda/3d/cone_bp.cu
cuda/3d/cone_fp.cu
cuda/3d/fdk.cu
cuda/3d/par3d_bp.cu
cuda/3d/par3d_fp.cu
cuda/3d/util3d.cu
include/astra/cuda/2d/arith.h
include/astra/cuda/2d/astra.h
include/astra/cuda/2d/fft.h
include/astra/cuda/2d/util.h
include/astra/cuda/3d/arith3d.h
include/astra/cuda/3d/util3d.h
src/CudaDataOperationAlgorithm.cpp

This adds stream support to CUDA utility functions, and improves various related things.
Many of them now take a `std::optional<cudaStream_t>` argument. If a stream is passed, the function will work on that stream, and might be asynchronous. If no stream is passed (which is the default), it will create its own stream, use that, and synchronize on that stream at the end of the function.
Using non-default streams everywhere prepares for using asynchronous memory transfers, and also will let the 'main' cuda functions use a single stream in the future. (These things are not part of this PR.)
Additionally, this is making more functions use similar code patterns and improves CUDA error handling.

Improve CUDA stream handling

---

build/linux/Makefile.in
include/astra/Data3D.h
lib/include/dlpack/dlpack.h
lib/licenses/dlpack.txt
python/astra/CFloat32CustomPython.h
python/astra/data2d.py
python/astra/data3d.py
python/astra/data3d_c.pyx
python/astra/matlab.py
python/astra/src/dlpack.cpp
python/astra/src/dlpack.h
python/astra/utils.pyx
python/builder.py
tests/python/integration/test_dlpack.py

This PR adds initial DLPack support to `astra.data3d.link()`, and to `astra.experimental.direct_FP3D/BP3D`. This makes it possible to directly use data from other libraries supporting the dlpack standard, such as numpy, torch, tensorflow and cupy. It supports CUDA and CPU arrays, and the dlpack 1.0 (versioned) standard as well as the pre-1.0 (unversioned) standard.
The previously existing numpy 3D link functionality now uses this dlpack code. The numpy 2D link functionality is unchanged.

Add support for DLPack arrays to data3d.link

---

cuda/3d/cone_bp.cu
cuda/3d/fdk.cu
cuda/3d/mem3d.cu
cuda/3d/par3d_bp.cu
include/astra/cuda/3d/astra3d.h
include/astra/cuda/3d/dims3d.h
include/astra/cuda/3d/mem3d.h
src/CompositeGeometryManager.cpp
src/CudaProjector3D.cpp
tests/python/functional/test_rec_scaling.py

This weights the backprojection to approximate the adjoint of the forward projection when using the 3d kernels to perform 2d operations (with a single slice in the Z direction).

Add 2d_weighting projection kernel to 3D backprojections

---

include/astra/Data3D.h
include/astra/Float32Data2D.h
src/Data3D.cpp
src/Float32Data2D.cpp

If I interpret what's happening correctly, with clang methods of template classes don't get instantiated if the class itself is instantiated before methods definition.

Fix building with clang

---

build/msvc/build_python3.bat
build/msvc/gen.py
build/msvc/projects/astra_mex_algorithm_vc14.vcxproj
build/msvc/projects/astra_mex_data2d_vc14.vcxproj
build/msvc/projects/astra_mex_data3d_vc14.vcxproj
build/msvc/projects/astra_mex_direct_vc14.vcxproj
build/msvc/projects/astra_mex_log_vc14.vcxproj
build/msvc/projects/astra_mex_matrix_vc14.vcxproj
build/msvc/projects/astra_mex_projector3d_vc14.vcxproj
build/msvc/projects/astra_mex_projector_vc14.vcxproj
build/msvc/projects/astra_mex_vc14.vcxproj
build/msvc/projects/astra_vc14.vcxproj

- Set `ASTRA_BUILDING_CUDA` in Windows project files to make CUDA build work. Probably related to #573.
- Add `"` around Python path to support spaces in path name

Fix Windows Build
